[package]
name = "sm2-demo-client"
version = "0.1.0"
edition = "2021"

[dependencies]
gm-rust = { path = "../../rust" }
ureq = { version = "2.9", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
